trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infra/terraform/**
      - pipelines/templates/stages/terraform-*.yml
      - azure-pipelines-infra.yml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - infra/terraform/**
      - pipelines/templates/stages/terraform-*.yml
      - azure-pipelines-infra.yml

variables:
  - group: enterprise-infra-secrets
  - name: environmentName
    value: dev
  - name: terraformWorkingDirectory
    value: infra/terraform
  - name: terraformVarFile
    value: environments/dev.tfvars
  - name: terraformStateKey
    value: gitops-platform/dev.tfstate

stages:
  - template: pipelines/templates/stages/terraform-validate.yml
    parameters:
      serviceName: platform-infra
      azureServiceConnection: $(azureServiceConnection)
      workingDirectory: $(terraformWorkingDirectory)
      vmImage: ubuntu-latest

  - template: pipelines/templates/stages/terraform-plan.yml
    parameters:
      serviceName: platform-infra
      azureServiceConnection: $(azureServiceConnection)
      workingDirectory: $(terraformWorkingDirectory)
      environmentName: $(environmentName)
      varFile: $(terraformVarFile)
      backendResourceGroupName: $(tfStateResourceGroup)
      backendStorageAccountName: $(tfStateStorageAccount)
      backendContainerName: $(tfStateContainer)
      backendStateKey: $(terraformStateKey)
      vmImage: ubuntu-latest

  - template: pipelines/templates/stages/terraform-apply.yml
    parameters:
      serviceName: platform-infra
      azureServiceConnection: $(azureServiceConnection)
      workingDirectory: $(terraformWorkingDirectory)
      environmentName: $(environmentName)
      backendResourceGroupName: $(tfStateResourceGroup)
      backendStorageAccountName: $(tfStateStorageAccount)
      backendContainerName: $(tfStateContainer)
      backendStateKey: $(terraformStateKey)
      enabled: true
      vmImage: ubuntu-latest

