trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  - group: enterprise-cicd-secrets
  - name: imageTag
    value: $(Build.BuildId)

stages:
  - template: pipelines/templates/stages/build.yml
    parameters:
      serviceName: calculator-api
      language: python
      runtimeVersion: "3.12"
      workingDirectory: .
      vmImage: ubuntu-latest
      artifactPath: src
      artifactName: drop
      sonarProjectKey: calculator-api
      enableSonarQube: true
      enableSecretScan: true
      preBuildSteps: []
      buildSteps:
        - bash: |
            python -m pip install --upgrade pip
            pip install coverage
            coverage run -m unittest discover -s tests
            coverage xml
            coverage report --fail-under=80
          displayName: Test Python service
      postBuildSteps: []

  - template: pipelines/templates/stages/security.yml
    parameters:
      serviceName: calculator-api
      vmImage: ubuntu-latest
      workingDirectory: .
      artifactName: drop
      veracodeApplicationProfile: calculator-api
      enableBlackDuck: true
      enableVeracode: true

  - template: pipelines/templates/stages/container.yml
    parameters:
      serviceName: calculator-api
      vmImage: ubuntu-latest
      dockerfile: Dockerfile
      dockerBuildContext: .
      imageRepository: gitops-calculator
      imageTag: $(Build.BuildId)
      enabled: true

  - template: pipelines/templates/stages/gitops.yml
    parameters:
      serviceName: calculator-api
      vmImage: ubuntu-latest
      imageTag: $(Build.BuildId)
      gitopsBranch: main
      gitopsValuesFile: environments/dev/values.yaml
      enabled: true
