apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-calculator-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops-calculator
  sources:
    - repoURL: REPLACE_GITOPS_REPOSITORY_URL
      targetRevision: main
      path: charts/gitops-calculator
      helm:
        valueFiles:
          - $values/environments/dev/values.yaml
    - repoURL: REPLACE_GITOPS_REPOSITORY_URL
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: calculator-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
