apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-calculator-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops-calculator
  sources:
    - repoURL: REPLACE_GITOPS_REPOSITORY_URL
      targetRevision: main
      path: charts/gitops-calculator
      helm:
        valueFiles:
          - $values/environments/staging/values.yaml
    - repoURL: REPLACE_GITOPS_REPOSITORY_URL
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: calculator-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
