parameters:
  - name: serviceName
    type: string
  - name: vmImage
    type: string
  - name: poolName
    type: string
    default: ""
  - name: poolDemands
    type: object
    default: []
  - name: dockerfile
    type: string
  - name: dockerBuildContext
    type: string
  - name: imageRepository
    type: string
  - name: imageTag
    type: string
  - name: enabled
    type: boolean

stages:
  - stage: Push
    displayName: Push image to ACR
    dependsOn: Security
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: PushToACR
        pool:
          ${{ if ne(parameters.poolName, '') }}:
            name: ${{ parameters.poolName }}
            ${{ if gt(length(parameters.poolDemands), 0) }}:
              demands:
                ${{ each demand in parameters.poolDemands }}:
                  - ${{ demand }}
          ${{ if eq(parameters.poolName, '') }}:
            vmImage: ${{ parameters.vmImage }}
        steps:
          - checkout: self
          - ${{ if eq(parameters.enabled, true) }}:
              - template: ../steps/docker-acr.yml
                parameters:
                  dockerfile: ${{ parameters.dockerfile }}
                  buildContext: ${{ parameters.dockerBuildContext }}
                  repository: ${{ parameters.imageRepository }}
                  imageTag: ${{ parameters.imageTag }}
          - ${{ if eq(parameters.enabled, false) }}:
              - bash: echo "Container publishing is disabled."
